[workspace]
resolver = "2"
members = ["common", "puzzles/*"]

[workspace.dependencies]
common = { path = "./common" }
clap = { version = "4.4.11", features = ["derive"] }
nom = "7.1.3"
itertools = "0.13.0"

